import { INodeProperties } from 'n8n-workflow';

export const bingLanguageList: INodeProperties = {
	displayName: 'Language',
	name: 'language',
	description: 'Select Language',
	default: 'en-US',
	type: 'options',
	options: [
		{ name: 'Argentina Spanish', value: 'es-AR' },
		{ name: 'Australia English', value: 'en-AU' },
		{ name: 'Austria German', value: 'de-AT' },
		{ name: 'Belgium Dutch', value: 'nl-BE' },
		{ name: 'Belgium French', value: 'fr-BE' },
		{ name: 'Brazil Portuguese', value: 'pt-BR' },
		{ name: 'Canada English', value: 'en-CA' },
		{ name: 'Canada French', value: 'fr-CA' },
		{ name: 'Chile Spanish', value: 'es-CL' },
		{ name: 'Denmark Danish', value: 'da-DK' },
		{ name: 'Finland Finnish', value: 'fi-FI' },
		{ name: 'France French', value: 'fr-FR' },
		{ name: 'Germany German', value: 'de-DE' },
		{ name: 'Hong Kong SAR Traditional Chinese', value: 'zh-HK' },
		{ name: 'India English', value: 'en-IN' },
		{ name: 'Indonesia English', value: 'en-ID' },
		{ name: 'Italy Italian', value: 'it-IT' },
		{ name: 'Japan Japanese', value: 'ja-JP' },
		{ name: 'Korea Korean', value: 'ko-KR' },
		{ name: 'Malaysia English', value: 'en-MY' },
		{ name: 'Mexico Spanish', value: 'es-MX' },
		{ name: 'Netherlands Dutch', value: 'nl-NL' },
		{ name: 'New Zealand English', value: 'en-NZ' },
		{ name: 'Norway Norwegian', value: 'no-NO' },
		{ name: 'China Chinese', value: 'zh-CN' },
		{ name: 'Poland Polish', value: 'pl-PL' },
		{ name: 'Portugal Portuguese', value: 'pt-PT' },
		{ name: 'Philippines English', value: 'en-PH' },
		{ name: 'Russia Russian', value: 'ru-RU' },
		{ name: 'Saudi Arabia Arabic', value: 'ar-SA' },
		{ name: 'South Africa English', value: 'en-ZA' },
		{ name: 'Spain Spanish', value: 'es-ES' },
		{ name: 'Sweden Swedish', value: 'sv-SE' },
		{ name: 'Switzerland French', value: 'fr-CH' },
		{ name: 'Switzerland German', value: 'de-CH' },
		{ name: 'Taiwan Traditional Chinese', value: 'zh-TW' },
		{ name: 'Turkey Turkish', value: 'tr-TR' },
		{ name: 'United Kingdom English', value: 'en-GB' },
		{ name: 'United States English', value: 'en-US' },
		{ name: 'United States Spanish', value: 'es-US' },
		{ name: 'India Hindi', value: 'hi-IN' },
		{ name: 'Belgium English', value: 'en-BE' },
	],
};
