import { INodeProperties } from 'n8n-workflow';

export const yahooDomainList: INodeProperties = {
	displayName: 'Domain',
	name: 'domain',
	type: 'options',
	default: 'be.yahoo.com',
	required: true,
	options: [
		{ name: 'be.yahoo.com', value: 'be.yahoo.com' },
		{ name: 'fr.yahoo.com', value: 'fr.yahoo.com' },
		{ name: 'br.yahoo.com', value: 'br.yahoo.com' },
		{ name: 'ca.yahoo.com', value: 'ca.yahoo.com' },
		{ name: 'de.yahoo.com', value: 'de.yahoo.com' },
		{ name: 'us.yahoo.com', value: 'us.yahoo.com' },
		{ name: 'es.yahoo.com', value: 'es.yahoo.com' },
		{ name: 'in.yahoo.com', value: 'in.yahoo.com' },
		{ name: 'id.yahoo.com', value: 'id.yahoo.com' },
		{ name: 'ie.yahoo.com', value: 'ie.yahoo.com' },
		{ name: 'it.yahoo.com', value: 'it.yahoo.com' },
		{ name: 'nl.yahoo.com', value: 'nl.yahoo.com' },
		{ name: 'no.yahoo.com', value: 'no.yahoo.com' },
		{ name: 'at.yahoo.com', value: 'at.yahoo.com' },
		{ name: 'ph.yahoo.com', value: 'ph.yahoo.com' },
		{ name: 'pl.yahoo.com', value: 'pl.yahoo.com' },
		{ name: 'qc.yahoo.com', value: 'qc.yahoo.com' },
		{ name: 'ro.yahoo.com', value: 'ro.yahoo.com' },
		{ name: 'ch.yahoo.com', value: 'ch.yahoo.com' },
		{ name: 'sg.yahoo.com', value: 'sg.yahoo.com' },
		{ name: 'za.yahoo.com', value: 'za.yahoo.com' },
		{ name: 'fi.yahoo.com', value: 'fi.yahoo.com' },
		{ name: 'se.yahoo.com', value: 'se.yahoo.com' },
		{ name: 'tr.yahoo.com', value: 'tr.yahoo.com' },
		{ name: 'uk.yahoo.com', value: 'uk.yahoo.com' },
		{ name: 'vn.yahoo.com', value: 'vn.yahoo.com' },
		{ name: 'gr.yahoo.com', value: 'gr.yahoo.com' },
		{ name: 'ru.yahoo.com', value: 'ru.yahoo.com' },
		{ name: 'ua.yahoo.com', value: 'ua.yahoo.com' },
		{ name: 'il.yahoo.com', value: 'il.yahoo.com' },
		{ name: 'hk.yahoo.com', value: 'hk.yahoo.com' },
		{ name: 'tw.yahoo.com', value: 'tw.yahoo.com' },
		{ name: 'malaysia.yahoo.com', value: 'malaysia.yahoo.com' },
		{ name: 'espanol.yahoo.com', value: 'espanol.yahoo.com' },
	],
};
