import { INodeProperties } from 'n8n-workflow';

export const yahooLanguageList: INodeProperties = {
	displayName: 'Language',
	name: 'language',
	description: 'Select Language',
	default: 'lang_en',
	type: 'options',
	options: [
		{ name: 'Arabic', value: 'lang_ar' },
		{ name: 'Bulgarian', value: 'lang_bg' },
		{ name: 'Chinese(Simplified)', value: 'lang_zh_chs' },
		{ name: 'Chinese(Traditional)', value: 'lang_zh_cht' },
		{ name: 'Croatian', value: 'lang_hr' },
		{ name: 'Czech', value: 'lang_cs' },
		{ name: 'Danish', value: 'lang_da' },
		{ name: 'Dutch', value: 'lang_nl' },
		{ name: 'English', value: 'lang_en' },
		{ name: 'Estonian', value: 'lang_et' },
		{ name: 'Finnish', value: 'lang_fi' },
		{ name: 'French', value: 'lang_fr' },
		{ name: 'German', value: 'lang_de' },
		{ name: 'Greek', value: 'lang_el' },
		{ name: 'Hebrew', value: 'lang_he' },
		{ name: 'Hungarian', value: 'lang_hu' },
		{ name: 'Italian', value: 'lang_it' },
		{ name: 'Japanese', value: 'lang_ja' },
		{ name: 'Korean', value: 'lang_ko' },
		{ name: 'Latvian', value: 'lang_lv' },
		{ name: 'Lithuanian', value: 'lang_lt' },
		{ name: 'Norwegian', value: 'lang_no' },
		{ name: 'Polish', value: 'lang_pl' },
		{ name: 'Portuguese', value: 'lang_pt' },
		{ name: 'Romanian', value: 'lang_ro' },
		{ name: 'Russian', value: 'lang_ru' },
		{ name: 'Slovak', value: 'lang_sk' },
		{ name: 'Slovenian', value: 'lang_sl' },
		{ name: 'Spanish', value: 'lang_es' },
		{ name: 'Swedish', value: 'lang_sv' },
		{ name: 'Thai', value: 'lang_th' },
		{ name: 'Turkish', value: 'lang_tr' },
	],
};
