import { INodeProperties } from 'n8n-workflow';

export const googleLanguageList: INodeProperties = {
	displayName: 'Language',
	name: 'language',
	description: 'Select Language',
	default: 'en',
	type: 'options',
	options: [
		{ name: 'Chinese (simplified)', value: 'zh_CN' },
		{ name: 'Chinese (traditional)', value: 'zh_TW' },
		{ name: 'Deutsch', value: 'de' },
		{ name: 'English', value: 'en' },
		{ name: 'español', value: 'es' },
		{ name: 'español (Latinoamérica)', value: 'es-419' },
		{ name: 'français', value: 'fr' },
		{ name: 'Croatian hrvatski', value: 'hr' },
		{ name: 'italiano', value: 'it' },
		{ name: 'Nederlands', value: 'nl' },
		{ name: 'polski', value: 'pl' },
		{ name: 'Portuguese', value: 'pt' },
		{ name: 'português (Brasil)', value: 'pt-BR' },
		{ name: 'português (Portugal)', value: 'pt-PT' },
		{ name: 'Vietnamese Tiếng Việt', value: 'vi' },
		{ name: 'Turkish (Türkçe)', value: 'tr' },
		{ name: 'Russian (русский)', value: 'ru' },
		{ name: 'Arabic (العربية)', value: 'ar' },
		{ name: 'Thai (ไทย)', value: 'th' },
		{ name: 'Korean (한국어)', value: 'ko' },
		{ name: '中文 (简体)', value: 'zh-CN' },
		{ name: '中文 (繁體)', value: 'zh-TW' },
		{ name: 'Japanese 日本語', value: 'ja' },
		{ name: 'Acoli', value: 'ach' },
		{ name: 'Afrikaans', value: 'af' },
		{ name: 'Akan', value: 'ak' },
		{ name: 'Asụsụ Igbo', value: 'ig' },
		{ name: 'azərbaycan', value: 'az' },
		{ name: 'Balinese', value: 'ban' },
		{ name: 'Basa Sunda', value: 'su' },
		{ name: 'Binisaya', value: 'ceb' },
		{ name: 'Bork, bork, bork!', value: 'xx-bork' },
		{ name: 'bosanski', value: 'bs' },
		{ name: 'brezhoneg', value: 'br' },
		{ name: 'Catalan català', value: 'ca' },
		{ name: 'Czech čeština', value: 'cs' },
		{ name: 'chiShona', value: 'sn' },
		{ name: 'Corsican', value: 'co' },
		{ name: 'Cymraeg', value: 'cy' },
		{ name: 'Danish dansk', value: 'da' },
		{ name: 'Èdè Yorùbá', value: 'yo' },
		{ name: 'eesti', value: 'et' },
		{ name: 'Elmer Fudd', value: 'xx-elmer' },
		{ name: 'esperanto', value: 'eo' },
		{ name: 'euskara', value: 'eu' },
		{ name: 'Eʋegbe', value: 'ee' },
		{ name: 'Filipino', value: 'fil' },
		{ name: 'føroyskt', value: 'fo' },
		{ name: 'Frysk', value: 'fy' },
		{ name: 'Ga', value: 'gaa' },
		{ name: 'Gaeilge', value: 'ga' },
		{ name: 'Gàidhlig', value: 'gd' },
		{ name: 'galego', value: 'gl' },
		{ name: 'Guarani', value: 'gn' },
		{ name: 'Hacker', value: 'xx-hacker' },
		{ name: 'Haitian Creole', value: 'ht' },
		{ name: 'Hausa', value: 'ha' },
		{ name: 'ʻŌlelo Hawaiʻi', value: 'haw' },
		{ name: 'Ichibemba', value: 'bem' },
		{ name: 'Ikirundi', value: 'rn' },
		{ name: 'Indonesia', value: 'id' },
		{ name: 'interlingua', value: 'ia' },
		{ name: 'isiXhosa', value: 'xh' },
		{ name: 'isiZulu', value: 'zu' },
		{ name: 'íslenska', value: 'is' },
		{ name: 'Jawa', value: 'jw' },
		{ name: 'Kinyarwanda', value: 'rw' },
		{ name: 'Kiswahili', value: 'sw' },
		{ name: 'Klingon', value: 'tlh' },
		{ name: 'Kongo', value: 'kg' },
		{ name: 'kreol morisien', value: 'mfe' },
		{ name: 'Krio (Sierra Leone)', value: 'kri' },
		{ name: 'Latin', value: 'la' },
		{ name: 'latviešu', value: 'lv' },
		{ name: 'lea fakatonga', value: 'to' },
		{ name: 'lietuvių', value: 'lt' },
		{ name: 'lingála', value: 'ln' },
		{ name: 'Lozi', value: 'loz' },
		{ name: 'Luba-Lulua', value: 'lua' },
		{ name: 'Luganda', value: 'lg' },
		{ name: 'magyar', value: 'hu' },
		{ name: 'Malagasy', value: 'mg' },
		{ name: 'Malti', value: 'mt' },
		{ name: 'Māori', value: 'mi' },
		{ name: 'Melayu', value: 'ms' },
		{ name: 'Nigerian Pidgin', value: 'pcm' },
		{ name: 'norsk', value: 'no' },
		{ name: 'Northern Sotho', value: 'nso' },
		{ name: 'Nyanja', value: 'ny' },
		{ name: 'nynorsk', value: 'nn' },
		{ name: "o'zbek", value: 'uz' },
		{ name: 'Occitan', value: 'oc' },
		{ name: 'Oromoo', value: 'om' },
		{ name: 'Pirate', value: 'xx-pirate' },
		{ name: 'română', value: 'ro' },
		{ name: 'rumantsch', value: 'rm' },
		{ name: 'Runasimi', value: 'qu' },
		{ name: 'Runyankore', value: 'nyn' },
		{ name: 'Seychellois Creole', value: 'crs' },
		{ name: 'shqip', value: 'sq' },
		{ name: 'slovenčina', value: 'sk' },
		{ name: 'slovenščina', value: 'sl' },
		{ name: 'Soomaali', value: 'so' },
		{ name: 'Southern Sotho', value: 'st' },
		{ name: 'srpski (Crna Gora)', value: 'sr-ME' },
		{ name: 'srpski (latinica)', value: 'sr-Latn' },
		{ name: 'suomi', value: 'fi' },
		{ name: 'svenska', value: 'sv' },
		{ name: 'Tswana', value: 'tn' },
		{ name: 'Tumbuka', value: 'tum' },
		{ name: 'türkmen dili', value: 'tk' },
		{ name: 'Twi', value: 'tw' },
		{ name: 'Wolof', value: 'wo' },
		{ name: 'Greek (Ελληνικά)', value: 'el' },
		{ name: 'Belarusian (беларуская)', value: 'be' },
		{ name: 'Bulgarian (български)', value: 'bg' },
		{ name: 'Kyrgyz (кыргызча)', value: 'ky' },
		{ name: 'Kazakh (қазақ тілі)', value: 'kk' },
		{ name: 'Macedonian (македонски)', value: 'mk' },
		{ name: 'монгол', value: 'mn' },
		{ name: 'Serbian (српски)', value: 'sr' },
		{ name: 'Tatar (татар)', value: 'tt' },
		{ name: 'Tajik (тоҷикӣ)', value: 'tg' },
		{ name: 'Ukrainian (українська)', value: 'uk' },
		{ name: 'Georgian (ქართული)', value: 'ka' },
		{ name: 'Armenian (հայերեն)', value: 'hy' },
		{ name: 'ייִדיש (jewish)', value: 'yi' },
		{ name: 'Abrit (עברית)', value: 'iw' },
		{ name: 'Uyghur (ئۇيغۇرچە)', value: 'ug' },
		{ name: 'Urdu - اردو', value: 'ur' },
		{ name: 'Pashto (پښتو)', value: 'ps' },
		{ name: 'سنڌي (Sindhi)', value: 'sd' },
		{ name: 'Persian (فارسی)', value: 'fa' },
		{ name: 'کوردیی ناوەندی', value: 'ckb' },
		{ name: 'Tigrinya (ትግርኛ)', value: 'ti' },
		{ name: 'Amharic (አማርኛ)', value: 'am' },
		{ name: 'Nepali (नेपाली)', value: 'ne' },
		{ name: 'Marathi (मराठी)', value: 'mr' },
		{ name: 'Hindi (हिन्दी)', value: 'hi' },
		{ name: 'Bengali (বাংলা)', value: 'bn' },
		{ name: 'ਪੰਜਾਬੀ', value: 'pa' },
		{ name: 'Gujarati (ગુજરાતી)', value: 'gu' },
		{ name: 'Oriya (ଓଡ଼ିଆ)', value: 'or' },
		{ name: 'Tamil (தமிழ்)', value: 'ta' },
		{ name: 'Telugu (తెలుగు)', value: 'te' },
		{ name: 'Kannada (ಕನ್ನಡ)', value: 'kn' },
		{ name: 'മലയാളം', value: 'ml' },
		{ name: 'the Sinhala (සිංහල)', value: 'si' },
		{ name: 'He ລາວ', value: 'lo' },
		{ name: 'Myanmar (မြန်မာ)', value: 'my' },
		{ name: 'Khmer (ខ្មែរ)', value: 'km' },
		{ name: 'ᏣᎳᎩ', value: 'chr' },
	],
};
